### ISSUE TITLE
Missing permission : Read message history

### ISSUE THREAD

**Issue by JM0unir** [ivanbeerlama/awesome_bot#1]
The bot also needs explicit `Read message history` permission so he can reply to requests

```
DiscordAPIError: Cannot reply without permission to read message history
    at RequestHandler.execute (/root/awesome_bot/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/root/awesome_bot/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
    at async TextChannel.send (/root/awesome_bot/node_modules/discord.js/src/structures/interfaces/TextBasedChannel.js:176:15) {
```

**Comment by ivanbeerlama** [comment]
Added to Readme.md, thanks!
